title:             Narashino 5chu CPC blog
email:              まだメールは無いよ@example.com
description:        技術的なことや学校生活の様子を発信している非公式ブログ。
author:           Narashino 5chu CPC
baseurl:            "/blog"
url:                "https://n5chu-ctech.github.io"

# Social Profiles
twitter_username:   
github_username:    n5chu-ctech
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
